### ISSUE TITLE
Add a Tic Tac Toe Game

### ISSUE THREAD

**Issue by alphadynamic00** [alphadynamic00/Js-Projects#21]
Add a good in UI tic tac toe game using javascript. 
Javascript is 😍.

**Comment by Bharat-kr** [comment]
I would Like to work on this issue Please assign me this Issue.

**Comment by Soumyajit2825** [comment]
assign me pls

**Comment by Mukul1235** [comment]
@alphadynamic00  I would like to work on this issue

**Comment by alphadynamic00** [comment]
You can give your pull request i will see whos is better ans add that one i just added ignore that if yours is better i will remove it. GO ahead.

**Comment by shrishti147** [comment]
please assign me.

**Comment by Soumyajit2825** [comment]
@alphadynamic00 done please review my PR
