### ISSUE TITLE
Image Gallery

### ISSUE THREAD

**Issue by alphadynamic00** [alphadynamic00/Js-Projects#30]
Add a Image Gallery Made using Javascript with a good UI.

**Comment by Abhishek12092002** [comment]
#Image Gallery
I want to add a image gallery using Js.
![image](https://user-images.githubusercontent.com/77578417/197698504-2deb5020-5a13-4ee5-abd3-4595d94fbb87.png)

**Comment by alphadynamic00** [comment]
Yes Please Go ahead.
